dist:
  - trusty

language:
  - cpp

sudo:
  - false

os:
  - osx

addons:
  apt:
    packages:
      - mlton
      - smlnj
      - libsmlnj-smlnj
      - polyml

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; brew install mlton polyml rlwrap ; brew cask install smlnj ; fi
      
script:
  - ./test/test.sh
